version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
    environment:
      DB_USER: postgres
      DB_PASSWORD: "1234"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: fastapi_magisterka
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB_NAME: magisterka_database

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: fastapi_magisterka
    ports:
      - "8090:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data:
